[tool.black]
line-length = 100
target-version = ["py36", "py37", "py38"]
extend-exclude = "^/src/nitsm/pinmapinterfaces.py"

[tool.ni-python-styleguide]
extend_exclude = "src/nitsm/pinmapinterfaces.py"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
markers = [
    "pin_map",
    "sequence_file",
    "offline_mode"
]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = clean, py3{6,7,8}-tests, py3{6,7,8}-systemtests, report

[testenv]
deps =
    pytest
    coverage
    nidcpower
    nidmm
    niscope
    nidigital
    niswitch
    nidaqmx
    nifgen
commands =
    tests: coverage run -m pytest tests --junitxml={envname}-results.xml
    systemtests: coverage run -m pytest systemtests --junitxml={envname}-results.xml
passenv =
    systemtests: TestStandPublic64 ProgramFiles(x86)
setenv =
    COVERAGE_FILE = .coverage.{envname}

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase

[testenv:report]
deps = coverage
skip_install = true
commands =
    coverage report
    coverage xml
"""
