# Checks pull request for proper code formatting and style
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Check code formatting with black
      run: |
        python -m pip install --upgrade black
        python -m black --check .

    - name: Lint with NI style guide
      run: |
        python -m pip install ni-python-styleguide==0.1.2
        python -m ni_python_styleguide lint
