name: Test Build and Install Package

on:
  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-install:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Build package
      uses: ./.github/actions/build

    - name: Install package
      run: |
        pip install pywin32  # install from pypi
        pip install nitsm --no-index -f dist/  # install local distribution
